### ISSUE TITLE
limit per ip?

### ISSUE THREAD

**Issue by naser** [BenediktMagnus/InstagramBotModule#1]
Hi,

Does this really work? does it need logging in to Instagram? and do you know if there is any limit on the number of requests per day? 

Thanks

**Comment by BenediktMagnus** [comment]
Yes, it really works.

You need to log in once (with a browser). After that, you can use the bot as long as the session cookie is valid.

I don't know about any limits. And I don't think they are public either. But as soon as you make too many requests you will look suspicious which could lead to a ban of the Instagram account in use (or worse). Instagram's terms of use forbid to automatically collect data of it's platform.

Therefore I encourage to read the terms of use and the corresponding laws of your country for you to know what you can and cannot do.
